name: test CD

on:
  push:
    tags:
        - v*-SNAPSHOT

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
            - 20.6.0

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - run: echo -n '${{ secrets.GCS_TUTOR_TEST }}' > tutor-test.json
        - run: npm install
        - run: npm run uploadGcsTest
